services:

  app_db:
    image: postgres
    container_name: app_db
    ports:
      - 5433:5432
    volumes: 
      - app_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vk_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - app_db
  
volumes:
  app_db_data: